### PR TITLE
avoid switch from mutable buffer to executable buffer back and forth

### PR DESCRIPTION
**Pull request by ailisp**
This only saves about 150ms of totally 2s wasmer compile many function module. 

`MemoryBuffer` is used twice. First it's created once and was `make_mut` and `make_exec` 150000 times. Second time it's created once per function, 150000 `MemoryBuffer`s created (`::new()`) and `make_mut` and `make_exec`. This is confirmed by the tracing. For the first one this optimization make it doesn't call `make_mut` and call `make_exec` once. For the second use it doesn't call `make_mut` but still 150000 times of `make_exec`. 

As a result, the new flamegraph showing there's `make_exec` make significant time, and besides that, a `copy_from_slice` , `munmap` and `wasmer_compiler_singlepass_near::codegen_x64::FuncGen::emit_trap` took all significant trunk of time (Ignore all by tracing spans). To see it: https://drive.google.com/file/d/1RXgNh_2ZAcnmX6nbWYHDMi6pTUK3J7tX/view?usp=sharing

Given this also drops an unused functionality (by wasmer, but it's dynasmrt public api): execute the buffer from a not finalized MemoryManager. There are a few ways to address it:
1. clone the mutable buffer, and make it executable for `reader`.
2. add a `with_reader_fn` api which takes a `f`, make the buffer executable, call `f` and make the buffer mutable again.
3. modify underlying memmap2 crate to make the buffer both executable and modifiable at the same time.

The first approach would make access to `reader` slower. And the first is not trivial because underlying mmap is not `Clone`.  The second approach also makes access to `reader` slower (compare to `reader` before this PR), but should be faster than first because avoid a clone. And the api is harder to use than the first approach. The third approach would also save all `make_exec`, but it breaks security guarantee claimed by dynasmrt: no buffer is made executable and modifiable at the same time. 

@matklad what do you think it's the best plan here?

### CODE REVIEW

**Comment by matklad** [comment]
Yeah, seeing 150_000 of *any* syscall here (mmap, munmap, etc) is not expected. Looking at the implementaion, it seems that the whole flow just ... doesn't make sense? 

We compile each function separately. We execute the following line for each function: 

https://github.com/near/wasmer/blob/58f9c68838f9773d2c8aa5c130cf421733689368/lib/compiler-singlepass/src/codegen_x64.rs#L1808

Inside `Assemble::new` we call an `mmap` to allocate pages of memeory where the jited code will leave. `Assembler` also does write/exec thing to the mapped pages, presumably because the use-case is that we'll *directly* execute the code in that mmaped region. 

However, in wasmer we just don't use that mmap and instead copy it out to `Vec<u8>` here: 

https://github.com/near/wasmer/blob/58f9c68838f9773d2c8aa5c130cf421733689368/lib/compiler-singlepass/src/codegen_x64.rs#L8674

When it comes to running the function, wasmer copies the bytes into mmaped memory managed by the wasmer runtime itself: 

https://github.com/near/wasmer/blob/58f9c68838f9773d2c8aa5c130cf421733689368/lib/engine-universal/src/code_memory.rs#L182

<hr/>

That is, dynasm actually provides us two bits of functionality: 

* codegen functionality, ability to encode instructions as a sequence of x86 opcodes in memory
* memory-management functionality, so that we can put the generated code into executable memory and actually jump to it. 

And it seems that wasmer only needs the first part here -- it completely disreagards any mmaping which dynasm does. 


So I think we want to do a bigger change here, and remove the memory management bits completely. Is there some `dynasm`  API which can be used to generated code into `Vec<u8>`, without creating mmaps and not using MemoryManager at all? If there isn't, would it be hard to add?

**Comment by ailisp** [comment]
@matklad Great insights! 
> So I think we want to do a bigger change here, and remove the memory management bits completely. Is there some dynasm API which can be used to generated code into Vec<u8>, without creating mmaps and not using MemoryManager at all? If there isn't, would it be hard to add?

Yes, dynasm have this API:
```
/// An assembler that assembles into a `Vec<u8>`, while supporting labels. To support the different types of relocations
/// it requires a base address of the to be assembled code to be specified.
#[derive(Debug)]
pub struct VecAssembler<R: Relocation> {
```
It has all features, except a MemoryManager than Assembler, will give a try!

**Comment by ailisp** [comment]
According to comment, VecAssembler doesn't work out of box, need a base address of the compiled code:
```
// in wasmer:
    /// The assembler.
    ///
    /// This should be changed to `Vec<u8>` for platform independency, but dynasm doesn't (yet)
    /// support automatic relative relocations for `Vec<u8>`.
    assembler: Assembler,
```

```
/// A full assembler implementation. Supports labels, all types of relocations, ...
#[derive(Debug)]
pub struct Assembler<R: Relocation> {

/// An assembler that assembles into a `Vec<u8>`, while supporting labels. To support the different types of relocations
/// it requires a base address of the to be assembled code to be specified.
#[derive(Debug)]
pub struct VecAssembler<R: Relocation> {
    ops: Vec<u8>,
    baseaddr: usize,
```

**Comment by matklad** [comment]
Yeah, we definitely need a base address if we use absolute addresses in the generated code. However, give that wasmer2 first generates code to the vec and then copies the vec to some specific address (which is know much later), it is clear that this is not required in general. 

Specifically, this works in wasmer because it uses this rellocation: 

https://github.com/CensoredUsername/dynasm-rs/blob/e10fb11e47e028422eb54fd55cea30af8fa7e0ad/runtime/src/relocations.rs#L39-L42

So practically, I think just passing `0` as a base address should work. A better solution would be to express "you don't need base address if you always use relative relocations" in types on dynasm side.

**Comment by ailisp** [comment]
Closed in favor of https://github.com/near/wasmer/pull/71

**Pull request closed without merging**
